version: 2
updates:
  # Check for updates to GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

      # Check for updates to Docker files
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
